### PR TITLE
Hey would you be fine if I merged your code

### PR DESCRIPTION
**Pull request by marvin1099**
I'm the main contributer of the wemod laucher right now and I like your code changes (excluding the tabs and spaces thing).
So I just want to ask you are you good with me merging your code.
The reason why I have asked you this that there will be a license change to AGPL3 soon and if you do not want your code to be AGPL3 then I will not merge your code.
Keep I mind I will pull your changes to my repo first and will change the length of the spaces or tabs to be inline with the current project, after that I will merge your branch to the official dev and main wemod-launcher branch.

Just tell how you feel about this.
You can also ignore this pull request I just did not know how to contact you so I used this pull request for that.

### CODE REVIEW

**Comment by Keyaku** [comment]
@marvin1099 Hello! For some reason, I wasn't notified of your comment, so I apologize for the huge delay.
Sure! You can merge my code, no problem. After a few updates, I realized the indentation was a bit breaking, so I was thinking in rebasing your code and applying my fixes.
How do you want to go about this?

**Comment by marvin1099** [comment]
Hey @Keyaku, if you could rebase to version  1.507 (newest one) and add those fixes.
That would help a lot for merging.
Thanks in advanced.

**Comment by marvin1099** [comment]
@Keyaku I see you have updated to the newest version already. Just add back those fixes and when you have added them let me know.
I will merge at that point.
Or you can also open a merge request after you have made those fixes.
I will then merge the code with the merge request.

**Comment by marvin1099** [comment]
@Keyaku 
About the readme line (you changed in the fix branch):
2. <ins>[OPTIONAL]</ins>: In case you'd like to use a different Proton-based layer than Valve's own Proton:

This should actually say something like: Use GE-Proton first and you can try your luck with Valve's own Proton.

As using GE-Proton seems to result in less user issues, so i prefer that.

**Comment by Keyaku** [comment]
@marvin1099 flatpak-dev is practically ready. It seems to work marvelously, but I would like to test some more.

**Comment by marvin1099** [comment]
Jep, take your time.
Just say when you are done.
Actually just open a pull request to the wemod-launcher.
Then I can also make some changes if need.
The flatpac dev version seems like I would merge like it is, but just in case make the pull request.

**Pull request merged**
